baseURL: 'https://djpm.xyz'
title: 'DjPM'

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true

markup:
  goldmark:
    renderer:
      unsafe: true
    renderHooks: 
      image:
        enableDefault: true
