main:
- name: Home
  url: /
  weight: 10
- name: About
  url: /about/
  weight: 20
- name: Publications
  url: /publications/
  weight: 30
- name: Talks
  url: /talks/
  weight: 40
- name: Projects 
  url: /projects/
  weight: 50
- name: Misc
  url: /misc/
  weight: 60