main:
- name: Home
  url: /
  weight: 10
- name: About
  url: /about/
  weight: 20
- name: Research
  url: /research/
  weight: 30
- name: Talks & Conferences
  url: /talks_conferences/
  weight: 40
- name: Other
  url: /other/
  weight: 50