main:
- name: Home
  url: /
  weight: 10
- name: Publications
  url: /publications/
  weight: 20
- name: Selected Talks
  url: /talks/
  weight: 30
- name: Personal Projects
  url: /projects/
  weight: 40