############################
## Author
############################

author:
  name: "Djordje Mihajlovic"
  image: cover_photo.jpg
  greeting: "I like maths and computers."

  icon: ":knot:"

############################
## Links
############################

links:
  - github: https://github.com/djordjepmihajlovic
  - orcid: https://orcid.org/0009-0008-7345-7681
  # - stack-overflow: https://math.stackexchange.com/users/1166352/djm
  - linkedin: https://www.linkedin.com/in/djordjemihajlovic00
  - strava: https://strava.app.link/SGbqaSCzYOb

###############################

title: "DjPM"
description: "Site built with Qubt & Hugo"